### ISSUE TITLE
Marshaling schemas with additionalProperties back from openapi3.T has extra fields

### ISSUE THREAD

**Issue by praneetloke** [cloudy-sky-software/pulumi-tailscale-native#164]
An object with `additionalProperties` in the original open API doc that looks like this:

```yaml
...
autoApprovers:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
...
```

turns into this when a doc loaded from that is serialized back into YAML:

```yaml
...
autoApprovers:
          type: object
          additionalProperties:
            has: null
            schema:
                type: array
                items:
                    type: string
...
```

Looks like kin-api needs a handler to marshal/unmarshal YAML similar to how it does with JSON. This causes validation of such schemas to fail because the `has` and the `schema` property under the `additionalProperties` object are treated as unknown "extras".
